language: python

python:
    - "2.7"
    - "3.4"

env:
    - "PYWR_SOLVER=glpk"
    - "PYWR_SOLVER=lpsolve"

before_install:
    - sudo apt-get update -qq

    # miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

    # dependencies
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib pytest dateutil pandas statsmodels networkx xlrd cython six ipython

    # system libraries
    - sudo apt-get install -qq libgmp3-dev libglpk-dev glpk liblpsolve55-dev lp-solve

    # remove lpsolve static library, which causes issues
    - sudo rm /usr/lib/liblpsolve55.a
    - sudo ln -s /usr/lib/lp_solve/liblpsolve55.so /usr/lib/liblpsolve55.so

install:
    - python setup.py install --with-${PYWR_SOLVER}

script:
    - py.test tests --solver ${PYWR_SOLVER}

notifications:
    email: false
