{% set name = "pywr" %}
{% set version = "0.6dev" %}

{% if os.environ.get("FEATURE_OLDGLIBC", "0") == "1" %}
{% set OLDGLIBC = 1 %}
{% else %}
{% set OLDGLIBC = 0 %}
{% endif %}

{% if os.environ.get("BUILD_DOC", "0") == "1" %}
{% set BUILD_DOC = 1 %}
{% else %}
{% set BUILD_DOC = 0 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0

  script_env:
    - FEATURE_OLDGLIBC [linux]
    - BUILD_DOC

  features:
  {% if OLDGLIBC %}
    - oldglibc
  {% endif %}


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - cython
    - glpk
    - lp_solve
    - future
    - packaging
    - wheel
    {% if OLDGLIBC %}
    - oldglibc
    {% endif %}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - networkx
    - glpk
    - lp_solve
    - pytables
    - xlrd
    - scipy
    - future
    - packaging
    - jupyter
    - matplotlib
    {% if OLDGLIBC %}
    - oldglibc
    {% endif %}

test:
  requires:
    - pytest
    - nbconvert
    {% if BUILD_DOC %}
    - sphinx
    - sphinx_rtd_theme
    - numpydoc
    {% endif %}

  source_files:
    - tests/*
    {% if BUILD_DOC %}
    - docs/*
    {% endif %}

about:
  home: https://github.com/pywr/pywr
  license: GPL
  license_file: LICENSE.txt
  summary: Water resource model written in Python
