package:
  name: pywr
  version: "0.1"

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
    - glpk
    - lpsolve
  run:
    - python
    - numpy x.x
    - pandas
    - networkx
    - glpk
    - lpsolve
    - pytables
    - xlrd

test:
  requires:
    - pytest

about:
  home: https://github.com/pywr/pywr
  license: GPL
  license_file: LICENSE.txt
  summary: Water resource model written in Python
