{% set name = "pywr" %}
{% set version = "0.4" %}

{% if os.environ.get("FEATURE_OLDGLIBC", "0") == "1" %}
{% set OLDGLIBC = 1 %}
{% else %}
{% set OLDGLIBC = 0 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0

  script_env:
    - FEATURE_OLDGLIBC [linux]

  {% if OLDGLIBC %}
  features:
    - oldglibc
  {% endif %}


requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
    - glpk
    - lpsolve
    - future
    - packaging
    {% if OLDGLIBC %}
    - oldglibc
    {% endif %}
  run:
    - python
    - numpy x.x
    - pandas
    - networkx
    - glpk
    - lpsolve
    - pytables
    - xlrd
    - scipy
    - future
    - packaging
    - jupyter
    - matplotlib
    {% if OLDGLIBC %}
    - oldglibc
    {% endif %}

test:
  requires:
    - pytest
    - nbconvert
  source_files:
    - tests/*

about:
  home: https://github.com/pywr/pywr
  license: GPL
  license_file: LICENSE.txt
  summary: Water resource model written in Python
