{% set name = "pywr" %}
{% set version = "0.2dev0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0

  script_env:
    - FEATURE_OLDGLIBC [linux]

  {% if os.environ.get("FEATURE_OLDGLIBC", "0") == "1" %}
  features:
    - oldglibc
  {% endif %}


requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
    - glpk
    - lpsolve
    - future
    - packaging
  run:
    - python
    - numpy x.x
    - pandas
    - networkx
    - glpk
    - lpsolve
    - pytables
    - xlrd
    - scipy
    - future
    - packaging

test:
  requires:
    - pytest

about:
  home: https://github.com/pywr/pywr
  license: GPL
  license_file: LICENSE.txt
  summary: Water resource model written in Python
